### ISSUE TITLE
PEN-1000.3.5.1 As a pool owner/user I need to be able to configure and reconfigure heater groups within the installation, so I can manage my pool/spa.

### ISSUE THREAD

**Issue by sevennote** [gryz/THW-Update-Needed#4]
https://pathfinder.atlassian.net/wiki/x/E4HuBQ

Feature circuit name limits are same as AUX circuits at 25 characters. 
adam[ 9:28 AM] 
@klewis03: what kind of response do you get back from the THW qa 1 locally if you run
{"command": "SetCommand", "method": "CreateGroup", "arguments": {"OBJTYP": "HCOMBO", "SNAME": "heater group","ACT": "PRIOR", "OBJLIST": [{ "objnam": "H878C",  "params": { "LISTORD": "1" } }]}}
(edited)
klewis03[ 9:31 AM ] I get this
klewis03[ 9:31 AM ] added a Plain Text snippet 
{"command": "Error","messageID": "3dbdffbe-db05-456d-82c1-8cb6f77bd653","response": "ParseError: Missing a name for object member."}
Add Comment 
adam
[ 9:34 AM ] sorry could you try it again, I was missing the double quotes around LISTORD, it returns 404 for me so I think the request is invalid. 
klewis03[ 9:34 AM ] i get a 400 back
[ 9:36 ] you have no message id
 [ 9:36 ] but i still get a 400
adam[ 9:37 AM ] 
using the simple websocket plugin, i have left off the message id when using it and it has not been a issue in the past but same thing with the message id, yep. (edited)
 [ 9:37 ] the H878C is a generic heater on qa1, so the circuit should be ok.
klewis03[ 9:38 AM ] I dont recall having an issue with it
adam[ 9:42 AM ] are you able to make a successful request call to create a heater group on your side?
klewis03[ 9:45 AM ] I will check it out
adam[ 9:45 AM ] cool, thanks
klewis03 [ 9:46 AM ] yup
klewis03[ 10:07 AM ] looks like circuits and lights work but heaters do not. I will have one of the devs look into it
adam[ 10:08 AM ] sounds good

**Comment by gryz** [comment]
Keith,

Any update on this ticket?

**Comment by klewis77** [comment]
This should be fixed as well

**Comment by acarnagey** [comment]
The newly created heater group does not show up in the getHardwareDefinition call:
{"command": "SetCommand", "method": "CreateGroup", "arguments": {"OBJTYP": "HCOMBO", "SNAME": "heater group","ACT": "PRIOR", "OBJLIST": [{ "objnam": "H7B00", "params": { "LISTORD": "1" } }]}}
{"response":"200","objectList":[{"objnam":"H7AEF","params":{"OBJTYP":"HEATER","SUBTYP":"HCOMBO","SNAME":"heater group","LISTORD":"LISTORD","SHOMNU":"","COUNT":"1","OBJLIST":[{"objnam":"hA58C","params":{"OBJTYP":"HCOMBO","PARENT":"H7AEF","USE":"H7B00","LISTORD":"1"}}]}}],"command":"SetCommand","messageID":""}
{"command":"GetQuery","queryName":"GetHardwareDefinition","arguments":"","messageID":"d8306df7-de1f-4dd7-8050-6e70c14b7698"}
{"answer":[{"objnam":"M0000","params":{"OBJTYP":"PANEL","SUBTYP":"OCP","HNAME":"OCP 0","SNAME":"OCP 0","LISTORD":"0","VER":"0.014","OBJLIST":[{"objnam":"m0020","params":{"OBJTYP":"MODULE","SUBTYP":"I10PS","SNAME":"I10PS","LISTORD":"1","PARENT":"M0000","PORT":"1","VER":"","BADGE":"BADGE","CIRCUITS":[{"objnam":"B66AC","params":{"OBJTYP":"BODY","SUBTYP":"SPA","SNAME":"Spa","LISTORD":"2","HITMP":"104","LOTMP":"100","HTSRC":"000FF","SHARE":"B09E6","PRIM":"00000","SEC":"00000","ACT1":"00000","ACT2":"00000","ACT3":"00000","ACT4":"00000","VOL":"0","MANHT":"00000"}},{"objnam":"C0300","params":{"OBJTYP":"CIRCUIT","SUBTYP":"GLOW","HNAME":"AUX6","SNAME":"GlowBrite 1","LISTORD":"9","PARENT":"m0020","BODY":"00000","FREEZE":"OFF","VER":"VER","TIMZON":"TIMZON","TIME":"720","RLY":"r0021","DNTSTP":"OFF","FEATR":"ON"}},{"objnam":"C705E","params":{"OBJTYP":"CIRCUIT","SUBTYP":"GENERIC","HNAME":"AUX9","SNAME":"AUX9","LISTORD":"7","PARENT":"m0020","BODY":"m0020","FREEZE":"OFF","VER":"VER","TIMZON":"TIMZON","TIME":"720","RLY":"r0024","DNTSTP":"OFF","FEATR":"OFF"}},{"objnam":"CDF65","params":{"OBJTYP":"CIRCUIT","SUBTYP":"GENERIC","HNAME":"AUX8","SNAME":"AUX8","LISTORD":"6","PARENT":"m0020","BODY":"m0020","FREEZE":"OFF","VER":"VER","TIMZON":"TIMZON","TIME":"720","RLY":"r0023","DNTSTP":"OFF","FEATR":"OFF"}},{"objnam":"CF28B","params":{"OBJTYP":"CIRCUIT","SUBTYP":"GENERIC","HNAME":"AUX7","SNAME":"AUX7","LISTORD":"5","PARENT":"m0020","BODY":"m0020","FREEZE":"OFF","VER":"VER","TIMZON":"TIMZON","TIME":"720","RLY":"r0022","DNTSTP":"OFF","FEATR":"OFF"}},{"objnam":"C66BB","params":{"OBJTYP":"CIRCUIT","SUBTYP":"GENERIC","HNAME":"AUX5","SNAME":"AUX5","LISTORD":"4","PARENT":"m0020","BODY":"m0020","FREEZE":"OFF","VER":"VER","TIMZON":"TIMZON","TIME":"720","RLY":"r0020","DNTSTP":"OFF","FEATR":"OFF"}},{"objnam":"VE762","params":{"SUBTYP":"LEGACY","SNAME":"RETURN (1)","COMUART":"COMUART","POSIT":"POSIT","ASSIGN":"RETURN","DLY":"OFF","OBJLIST":[{"objnam":"v7BE3","params":{"POSIT":"0","PRIOR":"0","CIRCUIT":"C411B"}},{"objnam":"v8DFF","params":{"POSIT":"1","PRIOR":"255","CIRCUIT":"C6EF6"}}]}},{"objnam":"VAE69","params":{"SUBTYP":"LEGACY","SNAME":"INTAKE (1)","COMUART":"COMUART","POSIT":"POSIT","ASSIGN":"INTAKE","DLY":"OFF","OBJLIST":[{"objnam":"v2C0E","params":{"POSIT":"0","PRIOR":"0","CIRCUIT":"C411B"}},{"objnam":"vF119","params":{"POSIT":"1","PRIOR":"255","CIRCUIT":"C6EF6"}}]}}]}},{"objnam":"m0000","params":{"OBJTYP":"MODULE","SUBTYP":"I5P","SNAME":"I5P","LISTORD":"0","PARENT":"M0000","PORT":"0","VER":"","BADGE":"BADGE","CIRCUITS":[{"objnam":"B09E6","params":{"OBJTYP":"BODY","SUBTYP":"POOL","SNAME":"Pool","LISTORD":"1","HITMP":"100","LOTMP":"82","HTSRC":"000FF","SHARE":"B66AC","PRIM":"CD21E","SEC":"C705E","ACT1":"00000","ACT2":"00000","ACT3":"00000","ACT4":"00000","VOL":"0","MANHT":"MANHT","OBJLIST":[{"objnam":"P68A2","params":{"OBJTYP":"PUMP","SUBTYP":"DUAL","SNAME":"Filter Pump","COMUART":"0","PRIMFLO":"0","PRIMTIM":"0","SYSTIM":"0","MIN":"0","MAX":"0","PRIOR":"SPEED","BODY":"B09E6","SHARE":"SHARE","DLY":"DLY","SETTMP":"0","OBJLIST":[{"objnam":"p9C0B","params":{"CIRCUIT":"CDCC0","LISTORD":"2","SPEED":"2","BOOST":"ON","SELECT":"NONE"}},{"objnam":"pB53C","params":{"CIRCUIT":"C411B","LISTORD":"1","SPEED":"0","BOOST":"OFF","SELECT":"NONE"}}]}},{"objnam":"IBA18","params":{"OBJTYP":"CHEM","SUBTYP":"ICHEM","SNAME":"Pool IntelliChem","COMUART":"1"}},{"objnam":"IFD01","params":{"OBJTYP":"CHEM","SUBTYP":"ICHLOR","SNAME":"Pool IntelliChlor","COMUART":"1"}}]}},{"objnam":"CD94A","params":{"OBJTYP":"CIRCUIT","SUBTYP":"INTELLI","HNAME":"AUX1","SNAME":"IntelliBrite 1","LISTORD":"10","PARENT":"m0000","BODY":"00000","FREEZE":"OFF","VER":"VER","TIMZON":"TIMZON","TIME":"720","RLY":"r0000","DNTSTP":"OFF","FEATR":"OFF"}},{"objnam":"CD21E","params":{"OBJTYP":"CIRCUIT","SUBTYP":"GENERIC","HNAME":"AUX4","SNAME":"AUX4","LISTORD":"3","PARENT":"m0000","BODY":"m0000","FREEZE":"OFF","VER":"VER","TIMZON":"TIMZON","TIME":"720","RLY":"r0003","DNTSTP":"OFF","FEATR":"OFF"}},{"objnam":"C44E7","params":{"OBJTYP":"CIRCUIT","SUBTYP":"GENERIC","HNAME":"AUX3","SNAME":"AUX3","LISTORD":"2","PARENT":"m0000","BODY":"m0000","FREEZE":"OFF","VER":"VER","TIMZON":"TIMZON","TIME":"720","RLY":"r0002","DNTSTP":"OFF","FEATR":"OFF"}},{"objnam":"C620C","params":{"OBJTYP":"CIRCUIT","SUBTYP":"GENERIC","HNAME":"AUX2","SNAME":"AUX2","LISTORD":"1","PARENT":"m0000","BODY":"m0000","FREEZE":"OFF","VER":"VER","TIMZON":"TIMZON","TIME":"720","RLY":"r0001","DNTSTP":"OFF","FEATR":"OFF"}},{"objnam":"V44A8","params":{"SUBTYP":"LEGACY","SNAME":"VALVE B(1)","COMUART":"COMUART","POSIT":"POSIT","ASSIGN":"VALVE","DLY":"OFF","OBJLIST":[{"objnam":"v3CE7","params":{"POSIT":"1","PRIOR":"1","CIRCUIT":"00000"}}]}},{"objnam":"VC1EC","params":{"SUBTYP":"LEGACY","SNAME":"VALVE A(1)","COMUART":"COMUART","POSIT":"POSIT","ASSIGN":"VALVE","DLY":"OFF","OBJLIST":[{"objnam":"v2495","params":{"POSIT":"1","PRIOR":"1","CIRCUIT":"00000"}}]}},{"objnam":"H7B00","params":{"OBJTYP":"HEATER","SUBTYP":"GENERIC","SNAME":"Gas Heater 1","LISTORD":"LISTORD"}},{"objnam":"A2BAB","params":{"OBJTYP":"SENSE","SUBTYP":"AIR","NAME":"AIR","SNAME":"AIR 3 Sensor","SOURCE":"83","PROBE":"83","CALIB":"0","LISTORD":"3"}},{"objnam":"A1986","params":{"OBJTYP":"SENSE","SUBTYP":"SOLAR","NAME":"SOLAR","SNAME":"SOLAR 2 Sensor","SOURCE":"82","PROBE":"82","CALIB":"0","LISTORD":"2"}},{"objnam":"A957E","params":{"OBJTYP":"SENSE","SUBTYP":"POOL","NAME":"WATER","SNAME":"POOL 1 Sensor","SOURCE":"82","PROBE":"82","CALIB":"0","LISTORD":"1"}}]}},{"objnam":"_A111","params":{"OBJTYP":"CIRCUIT","SUBTYP":"ALL","HNAME":"All Lights On","SNAME":"All Lights On","LISTORD":"0","PARENT":"00000","BODY":"00000","FREEZE":"OFF","VER":"VER","TIMZON":"TIMZON","TIME":"0","RLY":"RLY","DNTSTP":"OFF","FEATR":"OFF"}},{"objnam":"_A110","params":{"OBJTYP":"CIRCUIT","SUBTYP":"ALL","HNAME":"All Lights Off","SNAME":"All Lights Off","LISTORD":"0","PARENT":"00000","BODY":"00000","FREEZE":"OFF","VER":"VER","TIMZON":"TIMZON","TIME":"0","RLY":"RLY","DNTSTP":"OFF","FEATR":"OFF"}},{"objnam":"CAD2D","params":{"OBJTYP":"CIRCUIT","SUBTYP":"GENERIC","HNAME":"Circuit 1","SNAME":"FEA","LISTORD":"8","PARENT":"00000","BODY":"00000","FREEZE":"OFF","VER":"VER","TIMZON":"TIMZON","TIME":"60","RLY":"00000","DNTSTP":"OFF","FEATR":"ON"}},{"objnam":"CBE78","params":{"OBJTYP":"CIRCUIT","SUBTYP":"CIRCGRP","HNAME":"Circ Group 1","SNAME":"tjRb","LISTORD":"12","PARENT":"00000","BODY":"00000","FREEZE":"OFF","VER":"VER","TIMZON":"TIMZON","TIME":"720","RLY":"RLY","DNTSTP":"OFF","FEATR":"ON","OBJLIST":[{"objnam":"cA83A","params":{"OBJTYP":"CIRCGRP","CIRCUIT":"CF28B","ACT":"OFF","LISTORD":"1","DLY":"0"}},{"objnam":"c6694","params":{"OBJTYP":"CIRCGRP","CIRCUIT":"C705E","ACT":"ON","LISTORD":"1","DLY":"0"}}]}},{"objnam":"CC442","params":{"OBJTYP":"CIRCUIT","SUBTYP":"LITSHO","HNAME":"Light Show Group 1","SNAME":"light grp 1","LISTORD":"11","PARENT":"00000","BODY":"00000","FREEZE":"OFF","VER":"VER","TIMZON":"TIMZON","TIME":"720","RLY":"RLY","DNTSTP":"OFF","FEATR":"OFF","OBJLIST":[{"objnam":"cAED5","params":{"OBJTYP":"CIRCGRP","CIRCUIT":"CD94A","ACT":"WHITER","LISTORD":"1","DLY":"0"}}]}},{"objnam":"_FEA2","params":{"OBJTYP":"CIRCUIT","SUBTYP":"FRZ","HNAME":"Freeze","SNAME":"Freeze","LISTORD":"LISTORD","PARENT":"00000","BODY":"00000","FREEZE":"FREEZE","VER":"VER","TIMZON":"TIMZON","TIME":"TIME","RLY":"RLY","DNTSTP":"DNTSTP","FEATR":"FEATR"}},{"objnam":"P0FA9","params":{"OBJTYP":"PUMP","SUBTYP":"SINGLE","SNAME":"single speed","COMUART":"0","PRIMFLO":"0","PRIMTIM":"0","SYSTIM":"0","MIN":"0","MAX":"0","PRIOR":"SPEED","BODY":"00000","SHARE":"SHARE","DLY":"DLY","SETTMP":"0","OBJLIST":[{"objnam":"p52FF","params":{"CIRCUIT":"CDF65","LISTORD":"1","SPEED":"0","BOOST":"OFF","SELECT":"NONE"}}]}},{"objnam":"P129D","params":{"OBJTYP":"PUMP","SUBTYP":"DUAL","SNAME":"Lydia Pump","COMUART":"0","PRIMFLO":"0","PRIMTIM":"0","SYSTIM":"0","MIN":"0","MAX":"0","PRIOR":"SPEED","BODY":"00000","SHARE":"SHARE","DLY":"DLY","SETTMP":"0","OBJLIST":[{"objnam":"p1709","params":{"CIRCUIT":"C705E","LISTORD":"3","SPEED":"0","BOOST":"ON","SELECT":"NONE"}},{"objnam":"p4F9D","params":{"CIRCUIT":"C705E","LISTORD":"2","SPEED":"0","BOOST":"OFF","SELECT":"NONE"}},{"objnam":"p8E0F","params":{"CIRCUIT":"C705E","LISTORD":"1","SPEED":"0","BOOST":"ON","SELECT":"NONE"}}]}},{"objnam":"P9C78","params":{"OBJTYP":"PUMP","SUBTYP":"SPEED","SNAME":"Filter Pump 3","COMUART":"2","PRIMFLO":"2000","PRIMTIM":"1","SYSTIM":"0","MIN":"400","MAX":"3450","PRIOR":"SPEED","BODY":"00000","SHARE":"SHARE","DLY":"DLY","SETTMP":"10","OBJLIST":[{"objnam":"p301F","params":{"CIRCUIT":"CD21E","LISTORD":"2","SPEED":"2000","BOOST":"OFF","SELECT":"RPM"}},{"objnam":"p57BD","params":{"CIRCUIT":"C1B8E","LISTORD":"1","SPEED":"2000","BOOST":"ON","SELECT":"RPM"}}]}},{"objnam":"P2EE4","params":{"OBJTYP":"PUMP","SUBTYP":"FLOW","SNAME":"Filter Pump 2","COMUART":"1","PRIMFLO":"40","PRIMTIM":"1","SYSTIM":"15","MIN":"15","MAX":"134","PRIOR":"SPEED","BODY":"00000","SHARE":"SHARE","DLY":"DLY","SETTMP":"1","OBJLIST":[{"objnam":"pD806","params":{"CIRCUIT":"C705E","LISTORD":"1","SPEED":"40","BOOST":"OFF","SELECT":"GPM"}}]}},{"objnam":"_A135","params":{"OBJTYP":"SENSE","SUBTYP":"AIR","NAME":"AIR","SNAME":"Air Sensor","SOURCE":"83","PROBE":"83","CALIB":"0","LISTORD":"0"}}]}}],"queryName":"GetHardwareDefinition","command":"SendQuery","messageID":"d8306df7-de1f-4dd7-8050-6e70c14b7698","response":"200"}

**Comment by gryz** [comment]
So fixed or not?

**Comment by acarnagey** [comment]
Not fixed, it doesn't show up in getHardwareDefinition afterwards

**Comment by klewis77** [comment]
I have validated this is still an issue and well get a developer on it. So to be clear the issue is that after we create a heater group, the new group does not show up in the GetHardwareDefinition response.

**Comment by edgardoatpentair** [comment]
The heater group, H7AEF, is fixed will be show at getHardwareDefinition call:
see attachment.
[HeaterGroup.txt](https://github.com/gryz/THW-Update-Needed/files/374867/HeaterGroup.txt)

**Comment by acarnagey** [comment]
Same result, tested on fm qa 1 and dev1, here is dev1:
{"command": "SetCommand", "method": "CreateGroup", "arguments": {"OBJTYP": "HCOMBO", "SNAME": "heater group","ACT": "PRIOR", "OBJLIST": [{ "objnam": "H7B00", "params": { "LISTORD": "1" } }]}}
{"response":"200","objectList":[{"objnam":"H5983","params":{"OBJTYP":"HEATER","SUBTYP":"HCOMBO","SNAME":"heater group","LISTORD":"LISTORD","SHOMNU":"","COUNT":"1","OBJLIST":[{"objnam":"h462D","params":{"OBJTYP":"HCOMBO","PARENT":"H5983","USE":"H7B00","LISTORD":"1"}}]}}],"command":"SetCommand","messageID":""}

SocketService.js:91 Receiving: {"answer":[{"objnam":"M0000","params":{"OBJTYP":"PANEL","SUBTYP":"OCP","HNAME":"OCP 0","SNAME":"OCP 0","LISTORD":"0","VER":"0.014","OBJLIST":[{"objnam":"m0020","params":{"OBJTYP":"MODULE","SUBTYP":"I10PS","SNAME":"I10PS","LISTORD":"1","PARENT":"M0000","PORT":"1","VER":"","BADGE":"BADGE","CIRCUITS":[{"objnam":"B66AC","params":{"OBJTYP":"BODY","SUBTYP":"SPA","SNAME":"Spa","LISTORD":"2","HITMP":"104","LOTMP":"100","HTSRC":"000FF","SHARE":"B09E6","PRIM":"00000","SEC":"00000","ACT1":"00000","ACT2":"00000","ACT3":"00000","ACT4":"00000","VOL":"0","MANHT":"00000"}},{"objnam":"C0300","params":{"OBJTYP":"CIRCUIT","SUBTYP":"GLOW","HNAME":"AUX6","SNAME":"GlowBrite 1","LISTORD":"9","PARENT":"m0020","BODY":"00000","FREEZE":"OFF","VER":"VER","TIMZON":"TIMZON","TIME":"720","RLY":"r0021","DNTSTP":"OFF","FEATR":"ON"}},{"objnam":"C705E","params":{"OBJTYP":"CIRCUIT","SUBTYP":"GENERIC","HNAME":"AUX9","SNAME":"AUX9","LISTORD":"7","PARENT":"m0020","BODY":"m0020","FREEZE":"OFF","VER":"VER","TIMZON":"TIMZON","TIME":"720","RLY":"r0024","DNTSTP":"OFF","FEATR":"OFF"}},{"objnam":"CDF65","params":{"OBJTYP":"CIRCUIT","SUBTYP":"GENERIC","HNAME":"AUX8","SNAME":"AUX8","LISTORD":"6","PARENT":"m0020","BODY":"m0020","FREEZE":"OFF","VER":"VER","TIMZON":"TIMZON","TIME":"720","RLY":"r0023","DNTSTP":"OFF","FEATR":"OFF"}},{"objnam":"CF28B","params":{"OBJTYP":"CIRCUIT","SUBTYP":"GENERIC","HNAME":"AUX7","SNAME":"AUX7","LISTORD":"5","PARENT":"m0020","BODY":"m0020","FREEZE":"OFF","VER":"VER","TIMZON":"TIMZON","TIME":"720","RLY":"r0022","DNTSTP":"OFF","FEATR":"OFF"}},{"objnam":"C66BB","params":{"OBJTYP":"CIRCUIT","SUBTYP":"GENERIC","HNAME":"AUX5","SNAME":"AUX5","LISTORD":"4","PARENT":"m0020","BODY":"m0020","FREEZE":"OFF","VER":"VER","TIMZON":"TIMZON","TIME":"720","RLY":"r0020","DNTSTP":"OFF","FEATR":"OFF"}},{"objnam":"VE762","params":{"SUBTYP":"LEGACY","SNAME":"RETURN (1)","COMUART":"COMUART","POSIT":"POSIT","ASSIGN":"RETURN","DLY":"OFF","OBJLIST":[{"objnam":"v7BE3","params":{"POSIT":"0","PRIOR":"0","CIRCUIT":"C411B"}},{"objnam":"v8DFF","params":{"POSIT":"1","PRIOR":"255","CIRCUIT":"C6EF6"}}]}},{"objnam":"VAE69","params":{"SUBTYP":"LEGACY","SNAME":"INTAKE (1)","COMUART":"COMUART","POSIT":"POSIT","ASSIGN":"INTAKE","DLY":"OFF","OBJLIST":[{"objnam":"v2C0E","params":{"POSIT":"0","PRIOR":"0","CIRCUIT":"C411B"}},{"objnam":"vF119","params":{"POSIT":"1","PRIOR":"255","CIRCUIT":"C6EF6"}}]}}]}},{"objnam":"m0000","params":{"OBJTYP":"MODULE","SUBTYP":"I5P","SNAME":"I5P","LISTORD":"0","PARENT":"M0000","PORT":"0","VER":"","BADGE":"BADGE","CIRCUITS":[{"objnam":"B09E6","params":{"OBJTYP":"BODY","SUBTYP":"POOL","SNAME":"Pool","LISTORD":"1","HITMP":"100","LOTMP":"82","HTSRC":"H7B00","SHARE":"B66AC","PRIM":"CD21E","SEC":"C705E","ACT1":"00000","ACT2":"00000","ACT3":"00000","ACT4":"00000","VOL":"0","MANHT":"MANHT","OBJLIST":[{"objnam":"P68A2","params":{"OBJTYP":"PUMP","SUBTYP":"DUAL","SNAME":"Filter Pump","COMUART":"0","PRIMFLO":"0","PRIMTIM":"0","SYSTIM":"0","MIN":"0","MAX":"0","PRIOR":"SPEED","BODY":"B09E6","SHARE":"SHARE","DLY":"DLY","SETTMP":"0","OBJLIST":[{"objnam":"p9C0B","params":{"CIRCUIT":"CDCC0","LISTORD":"2","SPEED":"2","BOOST":"ON","SELECT":"NONE"}},{"objnam":"pB53C","params":{"CIRCUIT":"C411B","LISTORD":"1","SPEED":"0","BOOST":"OFF","SELECT":"NONE"}}]}},{"objnam":"IBA18","params":{"OBJTYP":"CHEM","SUBTYP":"ICHEM","SNAME":"Pool IntelliChem","COMUART":"1"}},{"objnam":"IFD01","params":{"OBJTYP":"CHEM","SUBTYP":"ICHLOR","SNAME":"Pool IntelliChlor","COMUART":"1"}}]}},{"objnam":"CD94A","params":{"OBJTYP":"CIRCUIT","SUBTYP":"INTELLI","HNAME":"AUX1","SNAME":"IntelliBrite 1","LISTORD":"10","PARENT":"m0000","BODY":"00000","FREEZE":"OFF","VER":"VER","TIMZON":"TIMZON","TIME":"720","RLY":"r0000","DNTSTP":"OFF","FEATR":"OFF"}},{"objnam":"CD21E","params":{"OBJTYP":"CIRCUIT","SUBTYP":"GENERIC","HNAME":"AUX4","SNAME":"AUX4","LISTORD":"3","PARENT":"m0000","BODY":"m0000","FREEZE":"OFF","VER":"VER","TIMZON":"TIMZON","TIME":"720","RLY":"r0003","DNTSTP":"OFF","FEATR":"OFF"}},{"objnam":"C44E7","params":{"OBJTYP":"CIRCUIT","SUBTYP":"GENERIC","HNAME":"AUX3","SNAME":"AUX3","LISTORD":"2","PARENT":"m0000","BODY":"m0000","FREEZE":"OFF","VER":"VER","TIMZON":"TIMZON","TIME":"720","RLY":"r0002","DNTSTP":"OFF","FEATR":"OFF"}},{"objnam":"C620C","params":{"OBJTYP":"CIRCUIT","SUBTYP":"GENERIC","HNAME":"AUX2","SNAME":"AUX2","LISTORD":"1","PARENT":"m0000","BODY":"m0000","FREEZE":"OFF","VER":"VER","TIMZON":"TIMZON","TIME":"720","RLY":"r0001","DNTSTP":"OFF","FEATR":"OFF"}},{"objnam":"V44A8","params":{"SUBTYP":"LEGACY","SNAME":"VALVE B(1)","COMUART":"COMUART","POSIT":"POSIT","ASSIGN":"VALVE","DLY":"OFF","OBJLIST":[{"objnam":"v3CE7","params":{"POSIT":"1","PRIOR":"1","CIRCUIT":"00000"}}]}},{"objnam":"VC1EC","params":{"SUBTYP":"LEGACY","SNAME":"VALVE A(1)","COMUART":"COMUART","POSIT":"POSIT","ASSIGN":"VALVE","DLY":"OFF","OBJLIST":[{"objnam":"v2495","params":{"POSIT":"1","PRIOR":"1","CIRCUIT":"00000"}}]}},{"objnam":"H7B00","params":{"OBJTYP":"HEATER","SUBTYP":"GENERIC","SNAME":"Gas Heater 1","LISTORD":"LISTORD"}},{"objnam":"A2BAB","params":{"OBJTYP":"SENSE","SUBTYP":"AIR","NAME":"AIR","SNAME":"AIR 3 Sensor","SOURCE":"84","PROBE":"84","CALIB":"0","LISTORD":"3"}},{"objnam":"A1986","params":{"OBJTYP":"SENSE","SUBTYP":"SOLAR","NAME":"SOLAR","SNAME":"SOLAR 2 Sensor","SOURCE":"84","PROBE":"84","CALIB":"0","LISTORD":"2"}},{"objnam":"A957E","params":{"OBJTYP":"SENSE","SUBTYP":"POOL","NAME":"WATER","SNAME":"POOL 1 Sensor","SOURCE":"83","PROBE":"83","CALIB":"0","LISTORD":"1"}}]}},{"objnam":"_A111","params":{"OBJTYP":"CIRCUIT","SUBTYP":"ALL","HNAME":"All Lights On","SNAME":"All Lights On","LISTORD":"0","PARENT":"00000","BODY":"00000","FREEZE":"OFF","VER":"VER","TIMZON":"TIMZON","TIME":"0","RLY":"RLY","DNTSTP":"OFF","FEATR":"OFF"}},{"objnam":"_A110","params":{"OBJTYP":"CIRCUIT","SUBTYP":"ALL","HNAME":"All Lights Off","SNAME":"All Lights Off","LISTORD":"0","PARENT":"00000","BODY":"00000","FREEZE":"OFF","VER":"VER","TIMZON":"TIMZON","TIME":"0","RLY":"RLY","DNTSTP":"OFF","FEATR":"OFF"}},{"objnam":"CAD2D","params":{"OBJTYP":"CIRCUIT","SUBTYP":"GENERIC","HNAME":"Circuit 1","SNAME":"FEA","LISTORD":"8","PARENT":"00000","BODY":"00000","FREEZE":"OFF","VER":"VER","TIMZON":"TIMZON","TIME":"60","RLY":"00000","DNTSTP":"OFF","FEATR":"ON"}},{"objnam":"CBE78","params":{"OBJTYP":"CIRCUIT","SUBTYP":"CIRCGRP","HNAME":"Circ Group 1","SNAME":"tjRb","LISTORD":"13","PARENT":"00000","BODY":"00000","FREEZE":"OFF","VER":"VER","TIMZON":"TIMZON","TIME":"720","RLY":"RLY","DNTSTP":"OFF","FEATR":"ON","OBJLIST":[{"objnam":"cA83A","params":{"OBJTYP":"CIRCGRP","CIRCUIT":"CF28B","ACT":"OFF","LISTORD":"1","DLY":"0"}},{"objnam":"c6694","params":{"OBJTYP":"CIRCGRP","CIRCUIT":"C705E","ACT":"ON","LISTORD":"1","DLY":"0"}}]}},{"objnam":"CC442","params":{"OBJTYP":"CIRCUIT","SUBTYP":"LITSHO","HNAME":"Light Show Group 1","SNAME":"light grp 1","LISTORD":"11","PARENT":"00000","BODY":"00000","FREEZE":"OFF","VER":"VER","TIMZON":"TIMZON","TIME":"720","RLY":"RLY","DNTSTP":"OFF","FEATR":"OFF","OBJLIST":[{"objnam":"cAED5","params":{"OBJTYP":"CIRCGRP","CIRCUIT":"CD94A","ACT":"WHITER","LISTORD":"1","DLY":"0"}}]}},{"objnam":"_FEA2","params":{"OBJTYP":"CIRCUIT","SUBTYP":"FRZ","HNAME":"Freeze","SNAME":"Freeze","LISTORD":"LISTORD","PARENT":"00000","BODY":"00000","FREEZE":"FREEZE","VER":"VER","TIMZON":"TIMZON","TIME":"TIME","RLY":"RLY","DNTSTP":"DNTSTP","FEATR":"FEATR"}},{"objnam":"C2354","params":{"OBJTYP":"CIRCUIT","SUBTYP":"CIRCGRP","HNAME":"Circ Group 1","SNAME":"test","LISTORD":"12","PARENT":"00000","BODY":"00000","FREEZE":"OFF","VER":"VER","TIMZON":"TIMZON","TIME":"720","RLY":"RLY","DNTSTP":"OFF","FEATR":"ON","OBJLIST":[{"objnam":"c58CF","params":{"OBJTYP":"CIRCGRP","CIRCUIT":"C705E","ACT":"ON","LISTORD":"1","DLY":"0"}}]}},{"objnam":"P0FA9","params":{"OBJTYP":"PUMP","SUBTYP":"SINGLE","SNAME":"single speed","COMUART":"0","PRIMFLO":"0","PRIMTIM":"0","SYSTIM":"0","MIN":"0","MAX":"0","PRIOR":"SPEED","BODY":"00000","SHARE":"SHARE","DLY":"DLY","SETTMP":"0","OBJLIST":[{"objnam":"p52FF","params":{"CIRCUIT":"CDF65","LISTORD":"1","SPEED":"0","BOOST":"OFF","SELECT":"NONE"}}]}},{"objnam":"P129D","params":{"OBJTYP":"PUMP","SUBTYP":"DUAL","SNAME":"Lydia Pump","COMUART":"0","PRIMFLO":"0","PRIMTIM":"0","SYSTIM":"0","MIN":"0","MAX":"0","PRIOR":"SPEED","BODY":"00000","SHARE":"SHARE","DLY":"DLY","SETTMP":"0","OBJLIST":[{"objnam":"p1709","params":{"CIRCUIT":"C705E","LISTORD":"3","SPEED":"0","BOOST":"ON","SELECT":"NONE"}},{"objnam":"p4F9D","params":{"CIRCUIT":"C705E","LISTORD":"2","SPEED":"0","BOOST":"OFF","SELECT":"NONE"}},{"objnam":"p8E0F","params":{"CIRCUIT":"C705E","LISTORD":"1","SPEED":"0","BOOST":"ON","SELECT":"NONE"}}]}},{"objnam":"P9C78","params":{"OBJTYP":"PUMP","SUBTYP":"SPEED","SNAME":"Filter Pump 3","COMUART":"2","PRIMFLO":"2000","PRIMTIM":"1","SYSTIM":"0","MIN":"400","MAX":"3450","PRIOR":"SPEED","BODY":"00000","SHARE":"SHARE","DLY":"DLY","SETTMP":"10","OBJLIST":[{"objnam":"p301F","params":{"CIRCUIT":"CD21E","LISTORD":"2","SPEED":"2000","BOOST":"OFF","SELECT":"RPM"}},{"objnam":"p57BD","params":{"CIRCUIT":"C1B8E","LISTORD":"1","SPEED":"2000","BOOST":"ON","SELECT":"RPM"}}]}},{"objnam":"P2EE4","params":{"OBJTYP":"PUMP","SUBTYP":"FLOW","SNAME":"Filter Pump 2","COMUART":"1","PRIMFLO":"40","PRIMTIM":"1","SYSTIM":"15","MIN":"15","MAX":"134","PRIOR":"SPEED","BODY":"00000","SHARE":"SHARE","DLY":"DLY","SETTMP":"1","OBJLIST":[{"objnam":"pD806","params":{"CIRCUIT":"C705E","LISTORD":"1","SPEED":"40","BOOST":"OFF","SELECT":"GPM"}}]}},{"objnam":"_A135","params":{"OBJTYP":"SENSE","SUBTYP":"AIR","NAME":"AIR","SNAME":"Air Sensor","SOURCE":"84","PROBE":"84","CALIB":"0","LISTORD":"0"}}]}}],"queryName":"GetHardwareDefinition","command":"SendQuery","messageID":"f4615b51-d812-4113-8153-e51555241d02","response":"200"}

**Comment by klewis77** [comment]
Heater Group now shows up in the GetHardwareDefinition
On DEV1

**Create**
```json
{
    "command": "SetCommand", 
    "messageID": "10A86ef1-88f1-8091-7cdf2b", 
    "method": "CreateGroup", 
    "arguments": {
        "OBJTYP": "HCOMBO", 
        "ACT": "CONCUR",
        "OBJLIST": [
           {
                "objnam": "H7B00", 
                "params": {
                    "LISTORD": "1"
                }
            } 
        ], 
        "SNAME": "Keith's Heater Group"
    }
}
```
**GetHardwareDefinition (Heater Goup is last element)**
```json
{
    "command": "SendQuery",
    "messageID": "10A86ef1-88f1-8091-7cdf1b",
    "queryName": "GetHardwareDefinition",
    "response": "200",
    "answer": [
        {
            "objnam": "M0000",
            "params": {
                "OBJTYP": "PANEL",
                "SUBTYP": "OCP",
                "HNAME": "OCP 0",
                "SNAME": "OCP 0",
                "LISTORD": "0",
                "VER": "0.014",
                "OBJLIST": [
                    {
                        "objnam": "m0020",
                        "params": {
                            "OBJTYP": "MODULE",
                            "SUBTYP": "I10PS",
                            "SNAME": "I10PS",
                            "LISTORD": "1",
                            "PARENT": "M0000",
                            "PORT": "1",
                            "VER": "",
                            "BADGE": "BADGE",
                            "CIRCUITS": [
                                {
                                    "objnam": "B66AC",
                                    "params": {
                                        "OBJTYP": "BODY",
                                        "SUBTYP": "SPA",
                                        "SNAME": "Spa",
                                        "LISTORD": "2",
                                        "HITMP": "104",
                                        "LOTMP": "100",
                                        "HTSRC": "000FF",
                                        "SHARE": "B09E6",
                                        "PRIM": "00000",
                                        "SEC": "00000",
                                        "ACT1": "00000",
                                        "ACT2": "00000",
                                        "ACT3": "00000",
                                        "ACT4": "00000",
                                        "VOL": "0",
                                        "MANHT": "00000"
                                    }
                                },
                                {
                                    "objnam": "C0300",
                                    "params": {
                                        "OBJTYP": "CIRCUIT",
                                        "SUBTYP": "GLOW",
                                        "HNAME": "AUX6",
                                        "SNAME": "GlowBrite 1",
                                        "LISTORD": "9",
                                        "PARENT": "m0020",
                                        "BODY": "00000",
                                        "FREEZE": "OFF",
                                        "VER": "VER",
                                        "TIMZON": "TIMZON",
                                        "TIME": "720",
                                        "RLY": "r0021",
                                        "DNTSTP": "OFF",
                                        "FEATR": "ON"
                                    }
                                },
                                {
                                    "objnam": "C705E",
                                    "params": {
                                        "OBJTYP": "CIRCUIT",
                                        "SUBTYP": "GENERIC",
                                        "HNAME": "AUX9",
                                        "SNAME": "AUX9",
                                        "LISTORD": "7",
                                        "PARENT": "m0020",
                                        "BODY": "m0020",
                                        "FREEZE": "OFF",
                                        "VER": "VER",
                                        "TIMZON": "TIMZON",
                                        "TIME": "720",
                                        "RLY": "r0024",
                                        "DNTSTP": "OFF",
                                        "FEATR": "OFF"
                                    }
                                },
                                {
                                    "objnam": "CDF65",
                                    "params": {
                                        "OBJTYP": "CIRCUIT",
                                        "SUBTYP": "GENERIC",
                                        "HNAME": "AUX8",
                                        "SNAME": "AUX8",
                                        "LISTORD": "6",
                                        "PARENT": "m0020",
                                        "BODY": "m0020",
                                        "FREEZE": "OFF",
                                        "VER": "VER",
                                        "TIMZON": "TIMZON",
                                        "TIME": "720",
                                        "RLY": "r0023",
                                        "DNTSTP": "OFF",
                                        "FEATR": "OFF"
                                    }
                                },
                                {
                                    "objnam": "CF28B",
                                    "params": {
                                        "OBJTYP": "CIRCUIT",
                                        "SUBTYP": "GENERIC",
                                        "HNAME": "AUX7",
                                        "SNAME": "AUX7",
                                        "LISTORD": "5",
                                        "PARENT": "m0020",
                                        "BODY": "m0020",
                                        "FREEZE": "OFF",
                                        "VER": "VER",
                                        "TIMZON": "TIMZON",
                                        "TIME": "720",
                                        "RLY": "r0022",
                                        "DNTSTP": "OFF",
                                        "FEATR": "OFF"
                                    }
                                },
                                {
                                    "objnam": "C66BB",
                                    "params": {
                                        "OBJTYP": "CIRCUIT",
                                        "SUBTYP": "GENERIC",
                                        "HNAME": "AUX5",
                                        "SNAME": "AUX5",
                                        "LISTORD": "4",
                                        "PARENT": "m0020",
                                        "BODY": "m0020",
                                        "FREEZE": "OFF",
                                        "VER": "VER",
                                        "TIMZON": "TIMZON",
                                        "TIME": "720",
                                        "RLY": "r0020",
                                        "DNTSTP": "OFF",
                                        "FEATR": "OFF"
                                    }
                                },
                                {
                                    "objnam": "VE762",
                                    "params": {
                                        "SUBTYP": "LEGACY",
                                        "SNAME": "RETURN (1)",
                                        "COMUART": "COMUART",
                                        "POSIT": "POSIT",
                                        "ASSIGN": "RETURN",
                                        "DLY": "OFF",
                                        "OBJLIST": [
                                            {
                                                "objnam": "v7BE3",
                                                "params": {
                                                    "POSIT": "0",
                                                    "PRIOR": "0",
                                                    "CIRCUIT": "C411B"
                                                }
                                            },
                                            {
                                                "objnam": "v8DFF",
                                                "params": {
                                                    "POSIT": "1",
                                                    "PRIOR": "255",
                                                    "CIRCUIT": "C6EF6"
                                                }
                                            }
                                        ]
                                    }
                                },
                                {
                                    "objnam": "VAE69",
                                    "params": {
                                        "SUBTYP": "LEGACY",
                                        "SNAME": "INTAKE (1)",
                                        "COMUART": "COMUART",
                                        "POSIT": "POSIT",
                                        "ASSIGN": "INTAKE",
                                        "DLY": "OFF",
                                        "OBJLIST": [
                                            {
                                                "objnam": "v2C0E",
                                                "params": {
                                                    "POSIT": "0",
                                                    "PRIOR": "0",
                                                    "CIRCUIT": "C411B"
                                                }
                                            },
                                            {
                                                "objnam": "vF119",
                                                "params": {
                                                    "POSIT": "1",
                                                    "PRIOR": "255",
                                                    "CIRCUIT": "C6EF6"
                                                }
                                            }
                                        ]
                                    }
                                }
                            ]
                        }
                    },
                    {
                        "objnam": "m0000",
                        "params": {
                            "OBJTYP": "MODULE",
                            "SUBTYP": "I5P",
                            "SNAME": "I5P",
                            "LISTORD": "0",
                            "PARENT": "M0000",
                            "PORT": "0",
                            "VER": "",
                            "BADGE": "BADGE",
                            "CIRCUITS": [
                                {
                                    "objnam": "B09E6",
                                    "params": {
                                        "OBJTYP": "BODY",
                                        "SUBTYP": "POOL",
                                        "SNAME": "Pool",
                                        "LISTORD": "1",
                                        "HITMP": "100",
                                        "LOTMP": "82",
                                        "HTSRC": "H7B00",
                                        "SHARE": "B66AC",
                                        "PRIM": "CD21E",
                                        "SEC": "C705E",
                                        "ACT1": "00000",
                                        "ACT2": "00000",
                                        "ACT3": "00000",
                                        "ACT4": "00000",
                                        "VOL": "0",
                                        "MANHT": "MANHT",
                                        "OBJLIST": [
                                            {
                                                "objnam": "P68A2",
                                                "params": {
                                                    "OBJTYP": "PUMP",
                                                    "SUBTYP": "DUAL",
                                                    "SNAME": "Filter Pump",
                                                    "COMUART": "0",
                                                    "PRIMFLO": "0",
                                                    "PRIMTIM": "0",
                                                    "SYSTIM": "0",
                                                    "MIN": "0",
                                                    "MAX": "0",
                                                    "PRIOR": "SPEED",
                                                    "BODY": "B09E6",
                                                    "SHARE": "SHARE",
                                                    "DLY": "DLY",
                                                    "SETTMP": "0",
                                                    "OBJLIST": [
                                                        {
                                                            "objnam": "p9C0B",
                                                            "params": {
                                                                "CIRCUIT": "CDCC0",
                                                                "LISTORD": "2",
                                                                "SPEED": "2",
                                                                "BOOST": "ON",
                                                                "SELECT": "NONE"
                                                            }
                                                        },
                                                        {
                                                            "objnam": "pB53C",
                                                            "params": {
                                                                "CIRCUIT": "C411B",
                                                                "LISTORD": "1",
                                                                "SPEED": "0",
                                                                "BOOST": "OFF",
                                                                "SELECT": "NONE"
                                                            }
                                                        }
                                                    ]
                                                }
                                            },
                                            {
                                                "objnam": "IBA18",
                                                "params": {
                                                    "OBJTYP": "CHEM",
                                                    "SUBTYP": "ICHEM",
                                                    "SNAME": "Pool IntelliChem",
                                                    "COMUART": "1"
                                                }
                                            },
                                            {
                                                "objnam": "IFD01",
                                                "params": {
                                                    "OBJTYP": "CHEM",
                                                    "SUBTYP": "ICHLOR",
                                                    "SNAME": "Pool IntelliChlor",
                                                    "COMUART": "1"
                                                }
                                            }
                                        ]
                                    }
                                },
                                {
                                    "objnam": "CD94A",
                                    "params": {
                                        "OBJTYP": "CIRCUIT",
                                        "SUBTYP": "INTELLI",
                                        "HNAME": "AUX1",
                                        "SNAME": "IntelliBrite 1",
                                        "LISTORD": "10",
                                        "PARENT": "m0000",
                                        "BODY": "00000",
                                        "FREEZE": "OFF",
                                        "VER": "VER",
                                        "TIMZON": "TIMZON",
                                        "TIME": "720",
                                        "RLY": "r0000",
                                        "DNTSTP": "OFF",
                                        "FEATR": "OFF"
                                    }
                                },
                                {
                                    "objnam": "CD21E",
                                    "params": {
                                        "OBJTYP": "CIRCUIT",
                                        "SUBTYP": "GENERIC",
                                        "HNAME": "AUX4",
                                        "SNAME": "AUX4",
                                        "LISTORD": "3",
                                        "PARENT": "m0000",
                                        "BODY": "m0000",
                                        "FREEZE": "OFF",
                                        "VER": "VER",
                                        "TIMZON": "TIMZON",
                                        "TIME": "720",
                                        "RLY": "r0003",
                                        "DNTSTP": "OFF",
                                        "FEATR": "OFF"
                                    }
                                },
                                {
                                    "objnam": "C44E7",
                                    "params": {
                                        "OBJTYP": "CIRCUIT",
                                        "SUBTYP": "GENERIC",
                                        "HNAME": "AUX3",
                                        "SNAME": "AUX3",
                                        "LISTORD": "2",
                                        "PARENT": "m0000",
                                        "BODY": "m0000",
                                        "FREEZE": "OFF",
                                        "VER": "VER",
                                        "TIMZON": "TIMZON",
                                        "TIME": "720",
                                        "RLY": "r0002",
                                        "DNTSTP": "OFF",
                                        "FEATR": "OFF"
                                    }
                                },
                                {
                                    "objnam": "C620C",
                                    "params": {
                                        "OBJTYP": "CIRCUIT",
                                        "SUBTYP": "GENERIC",
                                        "HNAME": "AUX2",
                                        "SNAME": "AUX2",
                                        "LISTORD": "1",
                                        "PARENT": "m0000",
                                        "BODY": "m0000",
                                        "FREEZE": "OFF",
                                        "VER": "VER",
                                        "TIMZON": "TIMZON",
                                        "TIME": "720",
                                        "RLY": "r0001",
                                        "DNTSTP": "OFF",
                                        "FEATR": "OFF"
                                    }
                                },
                                {
                                    "objnam": "V44A8",
                                    "params": {
                                        "SUBTYP": "LEGACY",
                                        "SNAME": "VALVE B(1)",
                                        "COMUART": "COMUART",
                                        "POSIT": "POSIT",
                                        "ASSIGN": "VALVE",
                                        "DLY": "OFF",
                                        "OBJLIST": [
                                            {
                                                "objnam": "v3CE7",
                                                "params": {
                                                    "POSIT": "1",
                                                    "PRIOR": "1",
                                                    "CIRCUIT": "00000"
                                                }
                                            }
                                        ]
                                    }
                                },
                                {
                                    "objnam": "VC1EC",
                                    "params": {
                                        "SUBTYP": "LEGACY",
                                        "SNAME": "VALVE A(1)",
                                        "COMUART": "COMUART",
                                        "POSIT": "POSIT",
                                        "ASSIGN": "VALVE",
                                        "DLY": "OFF",
                                        "OBJLIST": [
                                            {
                                                "objnam": "v2495",
                                                "params": {
                                                    "POSIT": "1",
                                                    "PRIOR": "1",
                                                    "CIRCUIT": "00000"
                                                }
                                            }
                                        ]
                                    }
                                },
                                {
                                    "objnam": "H7B00",
                                    "params": {
                                        "OBJTYP": "HEATER",
                                        "SUBTYP": "GENERIC",
                                        "SNAME": "Gas Heater 1",
                                        "LISTORD": "LISTORD"
                                    }
                                },
                                {
                                    "objnam": "A2BAB",
                                    "params": {
                                        "OBJTYP": "SENSE",
                                        "SUBTYP": "AIR",
                                        "NAME": "AIR",
                                        "SNAME": "AIR 3 Sensor",
                                        "SOURCE": "83",
                                        "PROBE": "83",
                                        "CALIB": "0",
                                        "LISTORD": "3"
                                    }
                                },
                                {
                                    "objnam": "A1986",
                                    "params": {
                                        "OBJTYP": "SENSE",
                                        "SUBTYP": "SOLAR",
                                        "NAME": "SOLAR",
                                        "SNAME": "SOLAR 2 Sensor",
                                        "SOURCE": "83",
                                        "PROBE": "83",
                                        "CALIB": "0",
                                        "LISTORD": "2"
                                    }
                                },
                                {
                                    "objnam": "A957E",
                                    "params": {
                                        "OBJTYP": "SENSE",
                                        "SUBTYP": "POOL",
                                        "NAME": "WATER",
                                        "SNAME": "POOL 1 Sensor",
                                        "SOURCE": "83",
                                        "PROBE": "83",
                                        "CALIB": "0",
                                        "LISTORD": "1"
                                    }
                                }
                            ]
                        }
                    },
                    {
                        "objnam": "_A111",
                        "params": {
                            "OBJTYP": "CIRCUIT",
                            "SUBTYP": "ALL",
                            "HNAME": "All Lights On",
                            "SNAME": "All Lights On",
                            "LISTORD": "0",
                            "PARENT": "00000",
                            "BODY": "00000",
                            "FREEZE": "OFF",
                            "VER": "VER",
                            "TIMZON": "TIMZON",
                            "TIME": "0",
                            "RLY": "RLY",
                            "DNTSTP": "OFF",
                            "FEATR": "OFF"
                        }
                    },
                    {
                        "objnam": "_A110",
                        "params": {
                            "OBJTYP": "CIRCUIT",
                            "SUBTYP": "ALL",
                            "HNAME": "All Lights Off",
                            "SNAME": "All Lights Off",
                            "LISTORD": "0",
                            "PARENT": "00000",
                            "BODY": "00000",
                            "FREEZE": "OFF",
                            "VER": "VER",
                            "TIMZON": "TIMZON",
                            "TIME": "0",
                            "RLY": "RLY",
                            "DNTSTP": "OFF",
                            "FEATR": "OFF"
                        }
                    },
                    {
                        "objnam": "C2354",
                        "params": {
                            "OBJTYP": "CIRCUIT",
                            "SUBTYP": "CIRCGRP",
                            "HNAME": "Circ Group 1",
                            "SNAME": "test",
                            "LISTORD": "12",
                            "PARENT": "00000",
                            "BODY": "00000",
                            "FREEZE": "OFF",
                            "VER": "VER",
                            "TIMZON": "TIMZON",
                            "TIME": "720",
                            "RLY": "RLY",
                            "DNTSTP": "OFF",
                            "FEATR": "ON",
                            "OBJLIST": [
                                {
                                    "objnam": "c58CF",
                                    "params": {
                                        "OBJTYP": "CIRCGRP",
                                        "CIRCUIT": "C705E",
                                        "ACT": "ON",
                                        "LISTORD": "1",
                                        "DLY": "0"
                                    }
                                }
                            ]
                        }
                    },
                    {
                        "objnam": "CAD2D",
                        "params": {
                            "OBJTYP": "CIRCUIT",
                            "SUBTYP": "GENERIC",
                            "HNAME": "Circuit 1",
                            "SNAME": "FEA",
                            "LISTORD": "8",
                            "PARENT": "00000",
                            "BODY": "00000",
                            "FREEZE": "OFF",
                            "VER": "VER",
                            "TIMZON": "TIMZON",
                            "TIME": "60",
                            "RLY": "00000",
                            "DNTSTP": "OFF",
                            "FEATR": "ON"
                        }
                    },
                    {
                        "objnam": "CBE78",
                        "params": {
                            "OBJTYP": "CIRCUIT",
                            "SUBTYP": "CIRCGRP",
                            "HNAME": "Circ Group 1",
                            "SNAME": "tjRb",
                            "LISTORD": "13",
                            "PARENT": "00000",
                            "BODY": "00000",
                            "FREEZE": "OFF",
                            "VER": "VER",
                            "TIMZON": "TIMZON",
                            "TIME": "720",
                            "RLY": "RLY",
                            "DNTSTP": "OFF",
                            "FEATR": "ON",
                            "OBJLIST": [
                                {
                                    "objnam": "cA83A",
                                    "params": {
                                        "OBJTYP": "CIRCGRP",
                                        "CIRCUIT": "CF28B",
                                        "ACT": "OFF",
                                        "LISTORD": "1",
                                        "DLY": "0"
                                    }
                                },
                                {
                                    "objnam": "c6694",
                                    "params": {
                                        "OBJTYP": "CIRCGRP",
                                        "CIRCUIT": "C705E",
                                        "ACT": "ON",
                                        "LISTORD": "1",
                                        "DLY": "0"
                                    }
                                }
                            ]
                        }
                    },
                    {
                        "objnam": "CC442",
                        "params": {
                            "OBJTYP": "CIRCUIT",
                            "SUBTYP": "LITSHO",
                            "HNAME": "Light Show Group 1",
                            "SNAME": "light grp 1",
                            "LISTORD": "11",
                            "PARENT": "00000",
                            "BODY": "00000",
                            "FREEZE": "OFF",
                            "VER": "VER",
                            "TIMZON": "TIMZON",
                            "TIME": "720",
                            "RLY": "RLY",
                            "DNTSTP": "OFF",
                            "FEATR": "OFF",
                            "OBJLIST": [
                                {
                                    "objnam": "cAED5",
                                    "params": {
                                        "OBJTYP": "CIRCGRP",
                                        "CIRCUIT": "CD94A",
                                        "ACT": "WHITER",
                                        "LISTORD": "1",
                                        "DLY": "0"
                                    }
                                }
                            ]
                        }
                    },
                    {
                        "objnam": "_FEA2",
                        "params": {
                            "OBJTYP": "CIRCUIT",
                            "SUBTYP": "FRZ",
                            "HNAME": "Freeze",
                            "SNAME": "Freeze",
                            "LISTORD": "LISTORD",
                            "PARENT": "00000",
                            "BODY": "00000",
                            "FREEZE": "FREEZE",
                            "VER": "VER",
                            "TIMZON": "TIMZON",
                            "TIME": "TIME",
                            "RLY": "RLY",
                            "DNTSTP": "DNTSTP",
                            "FEATR": "FEATR"
                        }
                    },
                    {
                        "objnam": "P0FA9",
                        "params": {
                            "OBJTYP": "PUMP",
                            "SUBTYP": "SINGLE",
                            "SNAME": "single speed",
                            "COMUART": "0",
                            "PRIMFLO": "0",
                            "PRIMTIM": "0",
                            "SYSTIM": "0",
                            "MIN": "0",
                            "MAX": "0",
                            "PRIOR": "SPEED",
                            "BODY": "00000",
                            "SHARE": "SHARE",
                            "DLY": "DLY",
                            "SETTMP": "0",
                            "OBJLIST": [
                                {
                                    "objnam": "p52FF",
                                    "params": {
                                        "CIRCUIT": "CDF65",
                                        "LISTORD": "1",
                                        "SPEED": "0",
                                        "BOOST": "OFF",
                                        "SELECT": "NONE"
                                    }
                                }
                            ]
                        }
                    },
                    {
                        "objnam": "P129D",
                        "params": {
                            "OBJTYP": "PUMP",
                            "SUBTYP": "DUAL",
                            "SNAME": "Lydia Pump",
                            "COMUART": "0",
                            "PRIMFLO": "0",
                            "PRIMTIM": "0",
                            "SYSTIM": "0",
                            "MIN": "0",
                            "MAX": "0",
                            "PRIOR": "SPEED",
                            "BODY": "00000",
                            "SHARE": "SHARE",
                            "DLY": "DLY",
                            "SETTMP": "0",
                            "OBJLIST": [
                                {
                                    "objnam": "p1709",
                                    "params": {
                                        "CIRCUIT": "C705E",
                                        "LISTORD": "3",
                                        "SPEED": "0",
                                        "BOOST": "ON",
                                        "SELECT": "NONE"
                                    }
                                },
                                {
                                    "objnam": "p4F9D",
                                    "params": {
                                        "CIRCUIT": "C705E",
                                        "LISTORD": "2",
                                        "SPEED": "0",
                                        "BOOST": "OFF",
                                        "SELECT": "NONE"
                                    }
                                },
                                {
                                    "objnam": "p8E0F",
                                    "params": {
                                        "CIRCUIT": "C705E",
                                        "LISTORD": "1",
                                        "SPEED": "0",
                                        "BOOST": "ON",
                                        "SELECT": "NONE"
                                    }
                                }
                            ]
                        }
                    },
                    {
                        "objnam": "P9C78",
                        "params": {
                            "OBJTYP": "PUMP",
                            "SUBTYP": "SPEED",
                            "SNAME": "Filter Pump 3",
                            "COMUART": "2",
                            "PRIMFLO": "2000",
                            "PRIMTIM": "1",
                            "SYSTIM": "0",
                            "MIN": "400",
                            "MAX": "3450",
                            "PRIOR": "SPEED",
                            "BODY": "00000",
                            "SHARE": "SHARE",
                            "DLY": "DLY",
                            "SETTMP": "10",
                            "OBJLIST": [
                                {
                                    "objnam": "p301F",
                                    "params": {
                                        "CIRCUIT": "CD21E",
                                        "LISTORD": "2",
                                        "SPEED": "2000",
                                        "BOOST": "OFF",
                                        "SELECT": "RPM"
                                    }
                                },
                                {
                                    "objnam": "p57BD",
                                    "params": {
                                        "CIRCUIT": "C1B8E",
                                        "LISTORD": "1",
                                        "SPEED": "2000",
                                        "BOOST": "ON",
                                        "SELECT": "RPM"
                                    }
                                }
                            ]
                        }
                    },
                    {
                        "objnam": "P2EE4",
                        "params": {
                            "OBJTYP": "PUMP",
                            "SUBTYP": "FLOW",
                            "SNAME": "Filter Pump 2",
                            "COMUART": "1",
                            "PRIMFLO": "40",
                            "PRIMTIM": "1",
                            "SYSTIM": "15",
                            "MIN": "15",
                            "MAX": "134",
                            "PRIOR": "SPEED",
                            "BODY": "00000",
                            "SHARE": "SHARE",
                            "DLY": "DLY",
                            "SETTMP": "1",
                            "OBJLIST": [
                                {
                                    "objnam": "pD806",
                                    "params": {
                                        "CIRCUIT": "C705E",
                                        "LISTORD": "1",
                                        "SPEED": "40",
                                        "BOOST": "OFF",
                                        "SELECT": "GPM"
                                    }
                                }
                            ]
                        }
                    },
                    {
                        "objnam": "_A135",
                        "params": {
                            "OBJTYP": "SENSE",
                            "SUBTYP": "AIR",
                            "NAME": "AIR",
                            "SNAME": "Air Sensor",
                            "SOURCE": "83",
                            "PROBE": "83",
                            "CALIB": "0",
                            "LISTORD": "0"
                        }
                    },
                    {
                        "objnam": "H5983",
                        "params": {
                            "OBJTYP": "HEATER",
                            "SUBTYP": "HCOMBO",
                            "SNAME": "heater group",
                            "DLY": "0",
                            "ACT": "CONCUR",
                            "OBJLIST": [
                                {
                                    "objnam": "h462D",
                                    "params": {
                                        "OBJTYP": "HCOMBO",
                                        "PARENT": "H5983",
                                        "USE": "H7B00",
                                        "LISTORD": "1"
                                    }
                                }
                            ]
                        }
                    },
                    {
                        "objnam": "H5592",
                        "params": {
                            "OBJTYP": "HEATER",
                            "SUBTYP": "HCOMBO",
                            "SNAME": "heater group",
                            "DLY": "0",
                            "ACT": "CONCUR",
                            "OBJLIST": [
                                {
                                    "objnam": "hF9E8",
                                    "params": {
                                        "OBJTYP": "HCOMBO",
                                        "PARENT": "H5592",
                                        "USE": "H7B00",
                                        "LISTORD": "1"
                                    }
                                }
                            ]
                        }
                    },
                    {
                        "objnam": "H5198",
                        "params": {
                            "OBJTYP": "HEATER",
                            "SUBTYP": "HCOMBO",
                            "SNAME": "Keith's Heater Group",
                            "DLY": "0",
                            "ACT": "CONCUR",
                            "OBJLIST": [
                                {
                                    "objnam": "h7E70",
                                    "params": {
                                        "OBJTYP": "HCOMBO",
                                        "PARENT": "H5198",
                                        "USE": "H7B00",
                                        "LISTORD": "1"
                                    }
                                }
                            ]
                        }
                    },
                    {
                        "objnam": "H7AEF",
                        "params": {
                            "OBJTYP": "HEATER",
                            "SUBTYP": "HCOMBO",
                            "SNAME": "heater group",
                            "DLY": "0",
                            "ACT": "CONCUR",
                            "OBJLIST": [
                                {
                                    "objnam": "hA58C",
                                    "params": {
                                        "OBJTYP": "HCOMBO",
                                        "PARENT": "H7AEF",
                                        "USE": "H7B00",
                                        "LISTORD": "1"
                                    }
                                }
                            ]
                        }
                    },
                    {
                        "objnam": "HB5CF",
                        "params": {
                            "OBJTYP": "HEATER",
                            "SUBTYP": "HCOMBO",
                            "SNAME": "heater group",
                            "DLY": "0",
                            "ACT": "CONCUR",
                            "OBJLIST": [
                                {
                                    "objnam": "hB557",
                                    "params": {
                                        "OBJTYP": "HCOMBO",
                                        "PARENT": "HB5CF",
                                        "USE": "H7B00",
                                        "LISTORD": "1"
                                    }
                                }
                            ]
                        }
                    },
                   {
                        "objnam": "HAA44",
                        "params": {
                            "OBJTYP": "HEATER",
                            "SUBTYP": "HCOMBO",
                            "SNAME": "Keith's Heater Group",
                            "DLY": "0",
                            "ACT": "CONCUR",
                            "OBJLIST": [
                                {
                                    "objnam": "h4834",
                                    "params": {
                                        "OBJTYP": "HCOMBO",
                                        "PARENT": "HAA44",
                                        "USE": "H7B00",
                                        "LISTORD": "1"
                                    }
                                }
                            ]
                        }
                    }
                ]
            }
        }
    ]
}
```

**Comment by acarnagey** [comment]
confirmed on my local
